### ISSUE TITLE
Invalid Address Bitcrack can only read keys that start with 1

### ISSUE THREAD

**Issue by TheRealLordFractal** [brichard19/BitCrack#140]
I tried running bitcrack against new key example 3DWi5UpHoP8JgXFZWXXdvUKWVmnyAa2xRB
 when I use bitcrack even though I know the private key, I get

Invalid Address:  3DWi5UpHoP8JgXFZWXXdvUKWVmnyAa2xRB

I changed the address not reflect actual address of account, but same rule applies, any address with 3 doesn't work with Bitcrack

**Comment by DrkAlien** [comment]
Addresses that starts with 1 are the first type of addresses that derives from 1 single private key ( that is a very large number, up to 75 numeric characters ). 
Addresses that start with 3 are multisig addresses, that requires more than 1 key to sign the transaction, in order to spend the coins. 
I don't think that this software is even built do such a job. 
3DWi5...etc addresses are used when you want multiple people to have acccess to Bitcoin, but they don't quite trust eachother.

**Comment by TheRealLordFractal** [comment]
I agree with you there, didn't think about that until after I posted.. I think maybe the best bang for the buck is to get windows 10 support for CUDA 10 so we can use tensor flow and getting better performance out of the nvidia RTX Cards.. I will those this.

**Comment by TheRealLordFractal** [comment]
Above Review, this is not necessary, to pursue the 3X address space as its double hash double keys.

**Comment by xdsswar** [comment]
I was about to test BitCrack and got few addresses from online but this one give error.
[Error] Invalid address '1aXzEKiDJKzkPxTZy9zGc3y1nCDwDPub2 	'

What's that mean? The address is valid , is a bug or that address is tricky? There is few more address like that.

Thanks in advance.
