### ISSUE TITLE
[Info] Error: the launch timed out and was terminated

### ISSUE THREAD

**Issue by voyagerlife** [brichard19/BitCrack#152]
After 5 hours process time I got this error.
And before that CMD closed itself 2 times, each was about after 2 hours.
Why does this happen?

**Comment by SatoshiNakamotoBitcoins** [comment]
@voyagerlife On what Card do you run??

**Comment by voyagerlife** [comment]
@SatoshiNakamotoBitcoins Asus GTX 1070 OC Strix

**Comment by voyagerlife** [comment]
Ok. apparently no idea..
Does anybody at least know how to start from the same point where it stopped? 
Brute forced keys amount (1,241,237,684,224 total)

**Comment by SatoshiNakamotoBitcoins** [comment]
@voyagerlife Hey...sorry for the late reaction.

It could be a heat issue...did you also experienced a "black" screen directly after the crash??
How many gigs of ram does your system has...I don't mean the ram of the GPU...and how much % did you used of the system ram at the time BitCrack jammed...

When you did applied the --continue flag you could go ahead from the point BitCrack jammed...otherwise you have to run it again.

Because you ran 1.241.237.684.224 keys it would be only 4 till 5 hours waste of time on your GTX 1070.

Cheers mate!!

**Comment by voyagerlife** [comment]
@SatoshiNakamotoBitcoins  Thanks mate!

**Comment by voyagerlife** [comment]
@SatoshiNakamotoBitcoins You're the biggest help for me! :) I just apply --continue flag in the command but it's then not starting. Just loading the file. Do you see any mistake at --continue part below?

C:\Users\PC\Desktop\BitCrack-master\BitCrack-master\x64\Release\cuBitCrack.exe -i C:\Users\PC\Documents\Addresses.txt -o C:\Users\Voyagers\Documents\Keys.txt --continue C:\Users\PC\Documents\save.txt

**Comment by SatoshiNakamotoBitcoins** [comment]
@voyagerlife thnx...the command is correct!

I assume that the value "next" and "end" in the save.txt file are the same; that's the reason why it's just loading the file and doesn't start.

My advise.. delete the current save.txt file...and apply the same command you mentioned before...that will creat also a "new" save.txt file, and run a new sequenze with BitCrack...the next time BitCrack jams again (ofcourse I don't hope so...;-)) and you apply the same command you mentioned before including the flag --continue save.txt it will start run again from the point the system has written the last hex to the save.txt file, ofcourse when the total keyspace hasn't reached yet...
