### ISSUE TITLE
[Question] regarding difference between the ECDSA computation process in the initializing base points process and doIteration 

### ISSUE THREAD

**Issue by BPatrick92** [brichard19/BitCrack#21]
Greetings @brichard19,

I am a beginner in both CUDA, C++ and Crypto operations and would appreciate if you could clarify some things.

I have been going through this repo. There are some fundamental concepts that I lack understanding in; what is the difference between the initial basepoint computation and the doIteration computation? More specifically, how come initializing is so much slower than iteration generation (even with the latest shift from the CPU to the GPU)? From my understanding you initialize base points, pass them to the GPU(s) - each individual thread in the grid will increment their base point. Upon incrementing in the doIteration computation you check to see if the new point is equal to the provided address.

1. How are you checking in the doIteration process without multiplying the point by the secp256k1 curve constant like you do in the addrGen repo (`secp256k1::ecpoint` p = secp256k1::multiplyPoint(k, `secp256k1::G());`)?

2. Why is the hash digest only 8 bytes when it should be 32 bytes (since it's SHA256)?

I am trying to feed custom private keys into your repo from a wordlist much like Brainflayer (https://github.com/ryancdotorg/brainflayer) but running on CUDA. I have been able to do so on a CPU using your AddrGen repo by hashing the wordlist password, converting to BIGNUM then loading into `secp256k1::uint256` and preforming all the other crypto operations.

**Comment by BPatrick92** [comment]
Additionally, I noticed that you are still verifying initial points on the CPU using `ecp256k1::multiplyPoint(k, secp256k1::G())` - is there a reason why this computation is not being done on the GPU?

**Comment by brichard19** [comment]
Hi,

> More specifically, how come initializing is so much slower than iteration generation (even with the latest shift from the CPU to the GPU)?

Because initialization uses point multiplication. There is a starting key `k`, and we can test `N` keys in parallel, so we need to compute `kG, (k+1)G, (k+2)G, ... (k+N-1)G`

The GPU does this with 256 iterations. For each iteration, it look at one bit of the private key. If it is 1, then add a multiple of G. If not, then do nothing. The first iteration adds `G`, the 2nd adds `2G`, the 3rd `4G`, all the way up to `(2^255)G`

> How are you checking in the doIteration process without multiplying the point by the secp256k1 curve constant like you do in the addrGen repo (secp256k1::ecpoint p = secp256k1::multiplyPoint(k, secp256k1::G());)?

Iteration only requires point addition. All the points have already been initialized to `kG, (k+1)G, (k+2)G, ... (k+N-1)G`. All points are incremented by `N x G`.

> Why is the hash digest only 8 bytes when it should be 32 bytes (since it's SHA256)?

The digest is 8 x 32-bit words.


> Additionally, I noticed that you are still verifying initial points on the CPU using ecp256k1::multiplyPoint(k, secp256k1::G()) - is there a reason why this computation is not being done on the GPU?

This verification is only done in debug builds in order to check that the secp256k1 library on the CPU agrees with the GPU.


I hope this clears things up. Let me know if you have more questions.


Thanks

**Comment by BPatrick92** [comment]
Thank you for your response, it was very helpful.
